<?php
include './admin/includes/connect.php';
?>
<!DOCTYPE html>
<html lang="vi" prefix="og: http://ogp.me/ns#"> <!--<![endif]-->

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="prerender" href="index.html" />


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />

    <link rel="icon" type="image/png" href="hinh_xe/favicon.ico" />
    <link rel="stylesheet" href="wp-content/themes/sterling/open-sans-gh-pages/open-sans.css" />

    <!-- This site is optimized with the Yoast SEO plugin v7.3 - https://yoast.com/wordpress/plugins/seo/ -->
    <title>ITBus</title>
    <meta name="description" content="Hành trình đảm bảo an toàn">
    <meta property="og:locale" content="vi_VN" />
    <meta property="og:type" content="website" />
</head>
<?php include("display/header_2.php") ?>
<!--styles generated by site options-->
<style type='text/css'>
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    .page-banner-heading,
    footer .foot-heading {
        font-family: 'Roboto', Arial, sans-serif;
        font-weight: 400;
    }

    #tt-boXed-layout {
        -moz-box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);
        -webkit-box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);
    }

    .top-aside {
        padding: 8px 0;
    }

    .small_banner {
        padding: 25px 0;
    }

    .footer-content {
        padding: 20px 0;
    }

    header {
        padding: 10px 0;
    }
</style>
<noscript>
    <style type="text/css">
        .wpb_animate_when_almost_visible {
            opacity: 1;
        }
    </style>
</noscript>
<script type="text/javascript" src="wp-content/themes/sterling/js.js"></script>

<!--[if IE 8]>
<style type="text/css" media="screen">
header .sub-menu {
      behavior: url(http://Xebongsenvang.vn/wp-content/themes/sterling/css/PIE/PIE.php);
}
</style>
<![endif]-->

<!--[if IE]>
    <link rel="stylesheet" href="http://Xebongsenvang.vn/wp-content/themes/sterling/css/IE.css" />
<![endif]-->

<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <script type="text/javascript" src="http://Xebongsenvang.vn/wp-content/themes/sterling/framework/js/IE.js"></script>
<![endif]-->

<!-- Styles generated by custom page styling options. -->
<style type="text/css">
    body,
</style>
<script type="text/javascript">
    jQuery.validator.setDefaults({
        errorElement: "span",
        errorClass: "help-block error",
        //  validClass: 'stay',
        highlight: function(element, errorClass, validClass) {
            jQuery(element).addClass(errorClass); //.removeClass(errorClass);
            jQuery(element).closest('.form-group').removeClass('has-success').addClass('error');
        },
        unhighlight: function(element, errorClass, validClass) {
            jQuery(element).removeClass(errorClass); //.addClass(validClass);
            jQuery(element).closest('.form-group').removeClass('error').addClass('has-success');
        },
        errorPlacement: function(error, element) {
            if (element.parent('.form-group').length) {
                error.insertAfter(element.parent());
            } else if (element.hasClass('select2')) {
                error.insertAfter(element.next('span'));
            } else {
                error.insertAfter(element);
            }
        }
    });

    jQuery(document).ready(function($) {

        $(".bolt-search").validate({
            ignore: [],
            rules: {
                startPoint: "required",
                endPoint: "required",
                startDate: "required",
            },
            messages: {
                startPoint: "Vui lòng chọn điểm đi",
                endPoint: "Vui lòng chọn điểm đến",
                startDate: "Vui lòng chọn ngày đi",
                fromHour: "Vui lòng chọn giờ đi",
            }
        });

        $(".bolt-search select").on("select2:close", function(e) {
            $(this).valid();
        });

        $('#startDate').focus(function(e) {
            $(this).valid();
            $('#startDate-error').addClass('vc_hide');
        })
        $('#startDate-error').each(function() {
            if ($(this).val() != '') {
                $(this).addClass('vc_hide');
            }
        })

        var dateToday = new Date();
        $('.banner-slider select').select2({
            placeholder: "Vui lòng chọn...",
            allowClear: true
        });


        $('#startDate').change(function() {
            $('#fromHour').select2("open");
        });

        $('#startPoint').on("select2:selecting", function(e) {
            if ($('#endPoint').val() == '') $('#endPoint').select2('open');

        });
        $('#endPoint').on("select2:selecting", function(e) {
            if ($('#startDate').val() == '') $('#startDate').trigger("click");
            $('#startDate-error').addClass('vc_hide');
            //$('#startDate-error').addClass('vc_hide');
        });

        $('#fromHour').each(function() {
            if ($(this).val() == '' && $('#startDate').val() != '') $(this).select2('open');

        });

        $('#startDate').click(function() {
            //$('#tcal').css({'margin-top': - $('#tcal').height()+50+'px'})
            //$('.admin-bar #tcal').css({'margin-top': - $('#tcal').height()+28+'px'})
            //$('html, body').stop().animate({scrollTop: $('#slider1_container').offset().top + 100}, 2000, 'easeInOutExpo');
        });

    });
</script>
<link rel="stylesheet" href="wp-content/themes/sterling/responsive.css" />

<!-- Google Tag Manager -->
<script>
    (function(w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({
            'gtm.start': new Date().getTime(),
            event: 'gtm.js'
        });
        var f = d.getElementsByTagName(s)[0],
            j = d.createElement(s),
            dl = l != 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src =
            'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
        f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-WHDH25Z');
</script>
<!-- End Google Tag Manager -->

</head>

<body class="archive post-type-archive post-type-archive-route wpb-js-composer js-comp-ver-4.11.2.1 vc_responsive">

    <div id="tt-wide-layout">
        <div id="tt-header-wrap">

        </div><!-- END #tt-header-wrap -->
        <section class="small_banner">
            <div class="center-wrap banner-no-crumbs">
                <p class="page-banner-heading"></p>

            </div><!-- end .center-wrap -->
            <div class="shadow top"></div>
            <div class="shadow bottom"></div>
            <div class="tt-overlay"></div>,
        </section>


        <?php


        if ($_SERVER["REQUEST_METHOD"] == "POST") {
            $diemdi = $_POST['diemdi'];
            $diemden = $_POST['diemden'];
            $date1 = strtr($_POST['ngaydi'], '/', '-');;
            $ngaydi = date("Y-m-d", strtotime($date1));
            $loaive = $_POST['loaive'];
            echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ngày đi : ", $_POST['ngaydi'], "<br><br>";

            echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ngày về : ", $_POST['ngayve'], "<br>";


            $sql = "Select Xe.tenXe,tenbendi,benden.tenben,khoihanh,lichtrinh.id from lichtrinh,Xe,benden,bendi where lichtrinh.bendi_id = bendi.id and lichtrinh.benden_id = benden.id and lichtrinh.maXe = Xe.id and benden_id=$diemden and bendi_id=$diemdi and chieudi=$loaive and ngaydi='$ngaydi'";

            if (isset($_POST['ngayve']) && !empty($_POST['ngayve'])) {

                $date2 = strtr($_POST['ngayve'], '/', '-');;
                $ngayve = date("Y-m-d", strtotime($date2));
                $sql .= "and ngayve='$ngayve'";
            }

            $rows = $db->query($sql);
            foreach ($rows as $r) {

        ?>

                <section id="content-container" class="clearfix">
                    <div class="center-wrap tt-relative clearfix">
                        <div class="section-list" id="Star-ha-noi">

                            <div class="table-responsive">
                                <table class="table  table-responsive">
                                    <thead>
                                        <tr class="text-white bg-success">
                                            <br> <br>
                                            <th>Bến đi</th>
                                            <th data-toggle="true">Bến đến</th>
                                            <th>Tên Xe</th>
                                            <th>Giờ xuất phát</th>
                                            <th>Chọn tầng</th>
                                            <th>chọn ghế</th>
                                            <th>giá vé</th>
                                            <th>thao tác</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        if (isset($_COOKIE["account_ibus"])) {
                                            echo '<form  method="get" action="thongtin.php">';
                                        } else {
                                            echo '<form >';
                                        }
                                        ?>

                                        <tr class="route-row532">
                                            <td><?php echo $r[1]; ?><input type="hidden" name="malichtrinh" value="<?php echo $r[4]; ?>"></td>
                                            <td><?php echo $r[2]; ?></td>
                                            <td><?php echo $r[0]; ?></td>
                                            <td><?php echo $r[3]; ?></td>
                                            <td> <select class="form-control" id="sotoa" name="sotoa" data-placeholder="Chontang" required>
                                                    <option selected disabled>chọn tầng</option>
                                                    <?php

                                                    $query = "select toa.id,tentoa from toa order by toa.id asc";
                                                    $rows = $db->query($query);
                                                    foreach ($rows as $r) {
                                                        echo "<option value='$r[0]'>$r[1]</option>";
                                                    }
                                                    ?>
                                                </select></td>
                                            <td style="text-align: center;"><select class="form-control" id="startPoint" name="soghe" data-placeholder="Chọn ghế" required>
                                                    <option selected disabled>Chọn ghế</option>
                                                    <?php

                                                    $query = "select ghe.id,soghe from ghe order by ghe.id asc";
                                                    $rows = $db->query($query);
                                                    foreach ($rows as $r) {
                                                        echo "<option value='$r[1]'>$r[1]</option>";
                                                    }
                                                    ?>
                                                </select></td>
                                            <td style="text-align: center;">400 000 VND</td>
                                            <td style="text-align: center;">
                                                <?php
                                                // if (isset($_COOKIE["account_ibus"])) {
                                                //     echo '<button type="submit">Đặt vé</button>';
                                                // } else {
                                                // }
                                                echo '<a class="btn_get_info" style="text-decoration: none;border:1px solid black;color:black;padding:3px 5px;" href="index?page=login">Đặt vé</a>';
                                                ?>
                                            </td>
                                        </tr>
                                        </form>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
        <?php  }
        }
        ?>
        <footer>
            <?php include("display/footer.php") ?>
        </footer>

        <script src="./get_info.js">
        </script>