<!DOCTYPE html>
<html lang="vi" prefix="og: http://ogp.me/ns#"> <!--<![endif]-->
<head>
<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="prerender" href="index.html"/>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />

<link rel="icon" type="image/png" href="hinh_xe/favicon.ico"/>
    <link rel="stylesheet" href="wp-content/themes/sterling/open-sans-gh-pages/open-sans.css" /> 
    
<!-- This site is optimized with the Yoast SEO plugin v7.3 - https://yoast.com/wordpress/plugins/seo/ -->
<title>ITBus</title>
<meta name="description" content="Hành trình đảm bảo an toàn">
<meta property="og:locale" content="vi_VN" />
<meta property="og:type" content="website" />

<!-- <link rel="alternate" type="application/rss+xml" title="Dòng thông tin Xe khách Bông Sen Vàng &raquo;" href="feed/index.rss" /> -->
<style type="text/css">img.wp-smiley,
img.emoji {
    display: inline !important;
    border: none !important;
    box-shadow: none !important;
    height: 1em !important;
    width: 1em !important;
    margin: 0 .07em !important;
    vertical-align: -0.1em !important;
    background: none !important;
    padding: 0 !important;
}
</style>
<link rel='stylesheet' id='breaking-nt-style-css'  href='wp-content/plugins/breaking-news-ticker/assets/css/ticker-style-ver=4.6.1.css' type='text/css' media='all' />
<link rel='stylesheet' id='js_composer_front-css'  href='wp-content/plugins/js_composer/assets/css/js_composer.min-ver=4.11.2.1.css' type='text/css' media='all' />
<script type='text/javascript' src='wp-includes/js/jquery/jquery-ver=1.12.4.js'></script>
<script type='text/javascript' src='wp-includes/js/jquery/jquery-migrate-ver=1.4.1.js'></script>
<script type='text/javascript' src='wp-content/plugins/breaking-news-ticker/assets/js/newsTicker.min-ver=1.js'></script>
<script type='text/javascript' src='wp-content/plugins/breaking-news-ticker/assets/js/jquery.easing.min-ver=1.js'></script>
<script type='text/javascript' src='wp-content/plugins/slider/js/jssor-ver=4.6.1.js'></script>
<script type='text/javascript' src='wp-content/plugins/slider/js/helper-ver=4.6.1.js'></script>
<link rel='https://api.w.org/' href='wp-json/index.html' />
<link rel='shortlink' href='index.html' />
<style type="text/css">.breaking-news-ticker {
        border-radius: 0px;
        border-style: solid;
        border-width: 0px;
        border-color: #259648;
        background-color: #259648;
    }

    .breaking-news-ticker ul li a,
    .breaking-news-ticker ul li a:link {
        color: #FFFFFF;
        font-size: 16px;
    }

    div.breaking-news-ticker .breaking-news-ticker-title {
        font-size: 15px;
        color: #FFFFFF;
        background-color: #259648;
    }

    div.breaking-news-ticker .breaking-news-ticker-title span {
        border-color: transparent transparent transparent #259648;
    }
    
    .breaking-news-ticker .controls {
        top: 5px;
    }

    .breaking-news-ticker .entry-meta {
        color:#FFFFFF;
    }

    .breaking-news-ticker .controls span {
        background-color: #217d3d   }

</style><link href="wp-content/themes/sterling/style.css" rel="stylesheet" type="text/css" media="screen" />
<link href="wp-content/themes/sterling/css/primary-blue.css" rel="stylesheet" type="text/css" media="screen" />
<link href="wp-content/themes/sterling/css/_mobile.css" rel="stylesheet" type="text/css" media="screen" />
<link href="wp-content/themes/sterling/css/_font-awesome.css" rel="stylesheet" type="text/css" media="screen" />
<link rel="shortcut icon" href="wp-content/uploads/2018/05/13620387_1753143234927573_7247147166338757397_n-2.jpg"/>
<meta name="generator" content="Powered by Visual Composer - drag and drop page builder for WordPress."/>
<!--[if lte IE 9]><link rel="stylesheet" type="text/css" href="http://xebongsenvang.vn/wp-content/plugins/js_composer/assets/css/vc_lte_ie9.min.css" media="screen"><![endif]--><!--[if IE  8]><link rel="stylesheet" type="text/css" href="http://xebongsenvang.vn/wp-content/plugins/js_composer/assets/css/vc-ie8.min.css" media="screen"><![endif]--><link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Roboto" />

<!--styles generated by site options-->
<style type='text/css'>h1, h2, h3, h4, h5, h6, .page-banner-heading, footer .foot-heading{font-family:'Roboto', Arial, sans-serif;font-weight:400;}

#tt-boxed-layout {-moz-box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);-webkit-box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);}
.top-aside{padding:8px 0;}
.small_banner {padding:25px 0;}
.footer-content {padding:20px 0;}
header {padding:10px 0;}
</style>
<noscript><style type="text/css">.wpb_animate_when_almost_visible { opacity: 1; }</style></noscript>    <script type="text/javascript" src="wp-content/themes/sterling/js.js"></script>

<!--[if IE 8]>
<style type="text/css" media="screen">
header .sub-menu {
      behavior: url(http://xebongsenvang.vn/wp-content/themes/sterling/css/PIE/PIE.php);
}
</style>
<![endif]-->

<!--[if IE]>
    <link rel="stylesheet" href="http://xebongsenvang.vn/wp-content/themes/sterling/css/IE.css" />
<![endif]-->

<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <script type="text/javascript" src="http://xebongsenvang.vn/wp-content/themes/sterling/framework/js/IE.js"></script>
<![endif]-->

<!-- Styles generated by custom page styling options. -->
<!-- <style type="text/css">body, html {background-color:# !important;}</style> -->
    <script type="text/javascript">
        jQuery.validator.setDefaults({
            errorElement: "span",
            errorClass: "help-block error",
            //  validClass: 'stay',
            highlight: function (element, errorClass, validClass) {
                jQuery(element).addClass(errorClass); //.removeClass(errorClass);
                jQuery(element).closest('.form-group').removeClass('has-success').addClass('error');
            },
            unhighlight: function (element, errorClass, validClass) {
                jQuery(element).removeClass(errorClass); //.addClass(validClass);
                jQuery(element).closest('.form-group').removeClass('error').addClass('has-success');
            },
            errorPlacement: function (error, element) {
                if (element.parent('.form-group').length) {
                    error.insertAfter(element.parent());
                } else if (element.hasClass('select2')) {
                    error.insertAfter(element.next('span'));
                } else {
                    error.insertAfter(element);
                }
            }
        });

        jQuery(document).ready(function($) {

            $(".bolt-search").validate({
                ignore: [],
                rules: {
                    startPoint: "required",
                    endPoint: "required",
                    startDate: "required",
                },
                messages: {
                    startPoint: "Vui lòng chọn điểm đi",
                    endPoint: "Vui lòng chọn điểm đến",
                    startDate: "Vui lòng chọn ngày đi",
                    fromHour: "Vui lòng chọn giờ đi",
                }
            });

            $(".bolt-search select").on("select2:close", function (e) {
                $(this).valid();
            });

            $('#startDate').focus(function (e) {
                $(this).valid();
                $('#startDate-error').addClass('vc_hide');
            })
            $('#startDate-error').each(function () {
                if ($(this).val() != ''){
                    $(this).addClass('vc_hide');
                }
            })

            var dateToday = new Date();
                        $('.banner-slider select').select2({
                placeholder: "Vui lòng chọn...",
                allowClear: true
            });
            
            /*$.datepicker.setDefaults($.datepicker.regional['vi']);
            $('#startDate').datepickerlunar({
                defaultDate: "+1w",
                numberOfMonths: 2,
                minDate: dateToday,
                dateFormat: "dd/mm/yy",
                 /*if(bolt_is_mb() == false) :
                onSelect: function () {
                    $('#fromHour').select2("open");

                }
                 /*endif;
            });*/
            $('#startDate').change(function () {
                $('#fromHour').select2("open");
            });

                        $('#startPoint').on("select2:selecting", function(e) {
                if($('#endPoint').val() =='') $('#endPoint').select2('open');

            });
            $('#endPoint').on("select2:selecting", function(e) {
                if($('#startDate').val() =='') $('#startDate').trigger("click");$('#startDate-error').addClass('vc_hide');
                //$('#startDate-error').addClass('vc_hide');
            });

            $('#fromHour').each(function() {
                if($(this).val() =='' && $('#startDate').val() !='') $(this).select2('open');

            });

            $('#startDate').click(function () {
                //$('#tcal').css({'margin-top': - $('#tcal').height()+50+'px'})
                //$('.admin-bar #tcal').css({'margin-top': - $('#tcal').height()+28+'px'})
                //$('html, body').stop().animate({scrollTop: $('#slider1_container').offset().top + 100}, 2000, 'easeInOutExpo');
            });
            
        });
    </script>
    <link rel="stylesheet" href="wp-content/themes/sterling/responsive.css" />

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WHDH25Z');</script>
<!-- End Google Tag Manager -->

</head>